import type { FormatProfileRecord } from './index';

export const LEDGER_VERSION = 3;

export const CONFIDENCE_THRESHOLD = 0.7;

export const SESSION_STORAGE_KEY = 'budgetapp_session_v1';

export const DEFAULT_CATEGORIES: string[] = [
  'Housing',
  'Groceries',
  'Transport',
  'Entertainment',
  'Utilities',
  'Telecoms',
  'Health & Fitness',
  'Shopping',
  'Personal Care',
  'Eating Out',
  'Travel',
  'Holidays',
  'Subscriptions',
  'Insurance',
  'Savings & Investments',
  'Fuel',
  'Taxes',
  'Income',
  'Internal Transfer',
  'Uncategorised',
];

/**
 * Descriptions matching this list (case-insensitive, exact match) are
 * non-transactional ledger markers and MUST be silently excluded from import.
 */
export const SKIP_LIST: string[] = ['OPENING BALANCE', 'CLOSING BALANCE'];

/** Ordered keyword → category mappings; first match wins (case-insensitive substring) */
export const DEFAULT_KEYWORD_MAP: Array<{ keyword: string; category: string }> = [
  // TV LICENCE — must precede Fuel section; 'BP' in Fuel would match 'MBP' in 'TV LICENCE MBP'
  { keyword: 'TV LICENCE', category: 'Utilities' },
  // Fuel overrides for grocery-branded fuel stations (must precede grocery keywords)
  { keyword: 'TESCO FUEL', category: 'Fuel' },
  { keyword: 'SAINSBURYS FUEL', category: 'Fuel' },
  { keyword: 'ASDA FUEL', category: 'Fuel' },
  { keyword: 'MORRISONS FUEL', category: 'Fuel' },
  // Shopping override — must precede ASDA → Groceries
  { keyword: 'GEORGE AT ASDA', category: 'Shopping' },
  // Groceries (TESCO MOBILE override must precede TESCO)
  { keyword: 'TESCO MOBILE', category: 'Telecoms' },
  { keyword: 'TESCO', category: 'Groceries' },
  { keyword: 'ASDA', category: 'Groceries' },
  { keyword: 'SAINSBURY', category: 'Groceries' },
  { keyword: 'MORRISONS', category: 'Groceries' },
  { keyword: 'WAITROSE', category: 'Groceries' },
  { keyword: 'ALDI', category: 'Groceries' },
  { keyword: 'LIDL', category: 'Groceries' },
  { keyword: 'CO-OP', category: 'Groceries' },
  { keyword: 'MARKS & SPENCER FOOD', category: 'Groceries' },
  { keyword: 'M&S FOOD', category: 'Groceries' },
  // Subscriptions (SKY MOBILE override must precede SKY)
  { keyword: 'NETFLIX', category: 'Subscriptions' },
  { keyword: 'SPOTIFY', category: 'Subscriptions' },
  { keyword: 'AMAZON PRIME', category: 'Subscriptions' },
  { keyword: 'DISNEY', category: 'Subscriptions' },
  { keyword: 'APPLE.COM/BILL', category: 'Subscriptions' },
  { keyword: 'NOW TV', category: 'Subscriptions' },
  { keyword: 'SKY MOBILE', category: 'Telecoms' },
  { keyword: 'SKY', category: 'Subscriptions' },
  { keyword: 'CLAUDE.AI', category: 'Subscriptions' },
  { keyword: 'ANTHROPIC', category: 'Subscriptions' },
  { keyword: 'CHATGPT', category: 'Subscriptions' },
  { keyword: 'OPENAI', category: 'Subscriptions' },
  { keyword: 'APPLE ONE', category: 'Subscriptions' },
  { keyword: 'GOOGLE ONE', category: 'Subscriptions' },
  { keyword: 'MICROSOFT 365', category: 'Subscriptions' },
  { keyword: 'OFFICE 365', category: 'Subscriptions' },
  { keyword: 'ADOBE', category: 'Subscriptions' },
  { keyword: 'DROPBOX', category: 'Subscriptions' },
  { keyword: 'ICLOUD', category: 'Subscriptions' },
  { keyword: 'YOUTUBE PREMIUM', category: 'Subscriptions' },
  { keyword: 'AUDIBLE', category: 'Subscriptions' },
  { keyword: 'DUOLINGO', category: 'Subscriptions' },
  { keyword: 'HEADSPACE', category: 'Subscriptions' },
  { keyword: 'CALM', category: 'Subscriptions' },
  // Eating Out (UBER EATS must precede UBER → Transport)
  { keyword: 'UBER EATS', category: 'Eating Out' },
  { keyword: 'COSTA', category: 'Eating Out' },
  { keyword: 'STARBUCKS', category: 'Eating Out' },
  { keyword: 'CAFE', category: 'Eating Out' },
  { keyword: 'GREGGS', category: 'Eating Out' },
  { keyword: 'MCDONALDS', category: 'Eating Out' },
  { keyword: 'BURGER KING', category: 'Eating Out' },
  { keyword: 'KFC', category: 'Eating Out' },
  { keyword: 'PIZZA', category: 'Eating Out' },
  { keyword: 'NANDOS', category: 'Eating Out' },
  { keyword: 'SUBWAY', category: 'Eating Out' },
  { keyword: 'DELIVEROO', category: 'Eating Out' },
  { keyword: 'JUST EAT', category: 'Eating Out' },
  { keyword: 'FIVE GUYS', category: 'Eating Out' },
  { keyword: 'WAGAMAMA', category: 'Eating Out' },
  { keyword: 'PRET A MANGER', category: 'Eating Out' },
  { keyword: 'LEON', category: 'Eating Out' },
  { keyword: 'ITSU', category: 'Eating Out' },
  { keyword: 'WASABI', category: 'Eating Out' },
  { keyword: 'YO SUSHI', category: 'Eating Out' },
  { keyword: 'HARVESTER', category: 'Eating Out' },
  { keyword: 'TOBY CARVERY', category: 'Eating Out' },
  { keyword: 'WEATHER SPOONS', category: 'Eating Out' },
  { keyword: 'WETHERSPOONS', category: 'Eating Out' },
  { keyword: 'PUB', category: 'Eating Out' },
  { keyword: 'BAR ', category: 'Eating Out' },
  { keyword: 'RESTAURANT', category: 'Eating Out' },
  // Entertainment (AMAZON GAMES must precede AMAZON → Shopping)
  { keyword: 'AMAZON GAMES', category: 'Entertainment' },
  { keyword: 'NATIONAL LOTTERY', category: 'Entertainment' },
  { keyword: 'LOTTERY', category: 'Entertainment' },
  { keyword: 'LOTTO', category: 'Entertainment' },
  { keyword: 'CINEMA', category: 'Entertainment' },
  { keyword: 'ODEON', category: 'Entertainment' },
  { keyword: 'VUE', category: 'Entertainment' },
  { keyword: 'CINEWORLD', category: 'Entertainment' },
  { keyword: 'THEATRE', category: 'Entertainment' },
  { keyword: 'TICKETMASTER', category: 'Entertainment' },
  { keyword: 'EVENTBRITE', category: 'Entertainment' },
  { keyword: 'STEAM', category: 'Entertainment' },
  { keyword: 'PLAYSTATION', category: 'Entertainment' },
  { keyword: 'XBOX', category: 'Entertainment' },
  { keyword: 'NINTENDO', category: 'Entertainment' },
  { keyword: 'APPLE ARCADE', category: 'Entertainment' },
  // Shopping (MARKS & SPENCER FOOD / M&S FOOD in Groceries section above take priority)
  { keyword: 'AMAZON', category: 'Shopping' },
  { keyword: 'EBAY', category: 'Shopping' },
  { keyword: 'ASOS', category: 'Shopping' },
  { keyword: 'H&M', category: 'Shopping' },
  { keyword: 'ZARA', category: 'Shopping' },
  { keyword: 'NEXT', category: 'Shopping' },
  { keyword: 'JOHN LEWIS', category: 'Shopping' },
  { keyword: 'PRIMARK', category: 'Shopping' },
  { keyword: 'IKEA', category: 'Shopping' },
  { keyword: 'MARKS & SPENCER', category: 'Shopping' },
  { keyword: 'M&S ', category: 'Shopping' },
  { keyword: 'DEBENHAMS', category: 'Shopping' },
  { keyword: 'RIVER ISLAND', category: 'Shopping' },
  { keyword: 'TOPSHOP', category: 'Shopping' },
  { keyword: 'NEW LOOK', category: 'Shopping' },
  { keyword: 'SPORTS DIRECT', category: 'Shopping' },
  { keyword: 'JD SPORTS', category: 'Shopping' },
  { keyword: 'FOOTLOCKER', category: 'Shopping' },
  { keyword: 'CURRYS', category: 'Shopping' },
  { keyword: 'ARGOS', category: 'Shopping' },
  { keyword: 'HALFORDS', category: 'Shopping' },
  { keyword: 'DUNELM', category: 'Shopping' },
  { keyword: 'MATALAN', category: 'Shopping' },
  // Transport
  { keyword: 'UBER', category: 'Transport' },
  { keyword: 'BOLT', category: 'Transport' },
  { keyword: 'TAXI', category: 'Transport' },
  { keyword: 'TRAINLINE', category: 'Transport' },
  { keyword: 'NATIONAL RAIL', category: 'Transport' },
  { keyword: 'TFL', category: 'Transport' },
  { keyword: 'BUS', category: 'Transport' },
  { keyword: 'AVANTI', category: 'Transport' },
  { keyword: 'GREAT WESTERN', category: 'Transport' },
  { keyword: 'SOUTHERN RAIL', category: 'Transport' },
  { keyword: 'SOUTHEASTERN', category: 'Transport' },
  { keyword: 'THAMESLINK', category: 'Transport' },
  { keyword: 'CHILTERN', category: 'Transport' },
  { keyword: 'CROSSCOUNTRY', category: 'Transport' },
  { keyword: 'NORTHERN RAIL', category: 'Transport' },
  { keyword: 'STAGECOACH', category: 'Transport' },
  { keyword: 'ARRIVA', category: 'Transport' },
  { keyword: 'FIRST BUS', category: 'Transport' },
  { keyword: 'CYCLE', category: 'Transport' },
  { keyword: 'LIME ', category: 'Transport' },
  { keyword: 'BIRD ', category: 'Transport' },
  { keyword: 'TIER ', category: 'Transport' },
  // Fuel
  { keyword: 'SHELL', category: 'Fuel' },
  { keyword: 'BP', category: 'Fuel' },
  { keyword: 'ESSO', category: 'Fuel' },
  { keyword: 'TEXACO', category: 'Fuel' },
  { keyword: 'MOTO', category: 'Fuel' },
  { keyword: 'FUEL', category: 'Fuel' },
  { keyword: 'MOTORWAY SERVICES', category: 'Fuel' },
  { keyword: 'WELCOME BREAK', category: 'Fuel' },
  { keyword: 'ROADCHEF', category: 'Fuel' },
  { keyword: 'EXTRA MSA', category: 'Fuel' },
  // Holidays
  { keyword: 'HOLIDAY INN', category: 'Holidays' },
  { keyword: 'AIRBNB', category: 'Holidays' },
  { keyword: 'BOOKING.COM', category: 'Holidays' },
  { keyword: 'EXPEDIA', category: 'Holidays' },
  { keyword: 'EASYJET', category: 'Holidays' },
  { keyword: 'RYANAIR', category: 'Holidays' },
  { keyword: 'BRITISH AIRWAYS', category: 'Holidays' },
  // Travel
  { keyword: 'HOTEL', category: 'Travel' },
  { keyword: 'HILTON', category: 'Travel' },
  { keyword: 'MARRIOTT', category: 'Travel' },
  { keyword: 'TRAVELODGE', category: 'Travel' },
  { keyword: 'PREMIER INN', category: 'Travel' },
  // Health & Fitness
  { keyword: 'GYM', category: 'Health & Fitness' },
  { keyword: 'FITNESS', category: 'Health & Fitness' },
  { keyword: 'PUREGYM', category: 'Health & Fitness' },
  { keyword: 'DAVID LLOYD', category: 'Health & Fitness' },
  { keyword: 'NUFFIELD', category: 'Health & Fitness' },
  { keyword: 'NHS', category: 'Health & Fitness' },
  { keyword: 'HOSPITAL', category: 'Health & Fitness' },
  { keyword: 'DOCTOR', category: 'Health & Fitness' },
  { keyword: 'BUPA', category: 'Health & Fitness' },
  // Personal Care
  { keyword: 'BOOTS', category: 'Personal Care' },
  { keyword: 'SUPERDRUG', category: 'Personal Care' },
  { keyword: 'PHARMACY', category: 'Personal Care' },
  { keyword: 'DENTIST', category: 'Personal Care' },
  // Internal Transfer — credit card settlement keywords placed before Housing
  // so that MORTGAGE PAYMENT → Internal Transfer rather than matching MORTGAGE → Housing
  { keyword: 'MORTGAGE PAYMENT', category: 'Internal Transfer' },
  { keyword: 'NATIONWIDE C/CARD', category: 'Internal Transfer' },
  { keyword: 'NATIONWIDE CREDIT', category: 'Internal Transfer' },
  { keyword: 'B/CARD', category: 'Internal Transfer' },
  { keyword: 'BARCLAYCARD', category: 'Internal Transfer' },
  { keyword: 'AMEX', category: 'Internal Transfer' },
  { keyword: 'AMERICAN EXPRESS', category: 'Internal Transfer' },
  { keyword: 'CAPITAL ONE', category: 'Internal Transfer' },
  { keyword: 'VANQUIS', category: 'Internal Transfer' },
  { keyword: 'AQUA CARD', category: 'Internal Transfer' },
  { keyword: 'VIRGIN MONEY CREDIT', category: 'Internal Transfer' },
  { keyword: 'MBNA', category: 'Internal Transfer' },
  { keyword: 'LOAN PAYMENT', category: 'Internal Transfer' },
  { keyword: 'CARD PAYMENT TO', category: 'Internal Transfer' },
  { keyword: 'ONLINE PAYMENT TO', category: 'Internal Transfer' },
  { keyword: 'STANDING ORDER TO', category: 'Internal Transfer' },
  { keyword: 'FASTER PAYMENT TO', category: 'Internal Transfer' },
  // Housing
  { keyword: 'MORTGAGE', category: 'Housing' },
  { keyword: 'RENT', category: 'Housing' },
  { keyword: 'GROUND RENT', category: 'Housing' },
  { keyword: 'SERVICE CHARGE', category: 'Housing' },
  { keyword: 'LETTING AGENT', category: 'Housing' },
  { keyword: 'ESTATE AGENT RENT', category: 'Housing' },
  // Utilities (specific energy names before generic EDF; NOW BROADBAND before BROADBAND)
  { keyword: 'OCTOPUS ENERGY', category: 'Utilities' },
  { keyword: 'EDF ENERGY', category: 'Utilities' },
  { keyword: 'OVO ENERGY', category: 'Utilities' },
  { keyword: 'NOW BROADBAND', category: 'Telecoms' },
  { keyword: 'GAS', category: 'Utilities' },
  { keyword: 'ELECTRIC', category: 'Utilities' },
  { keyword: 'WATER', category: 'Utilities' },
  { keyword: 'BROADBAND', category: 'Utilities' },
  { keyword: 'EDF', category: 'Utilities' },
  { keyword: 'BRITISH GAS', category: 'Utilities' },
  { keyword: 'EON', category: 'Utilities' },
  { keyword: 'E.ON', category: 'Utilities' },
  { keyword: 'NPOWER', category: 'Utilities' },
  { keyword: 'BULB', category: 'Utilities' },
  { keyword: 'BBC', category: 'Utilities' },
  { keyword: 'THAMES WATER', category: 'Utilities' },
  { keyword: 'ANGLIAN WATER', category: 'Utilities' },
  { keyword: 'SEVERN TRENT', category: 'Utilities' },
  { keyword: 'UNITED UTILITIES', category: 'Utilities' },
  { keyword: 'YORKSHIRE WATER', category: 'Utilities' },
  { keyword: 'WESSEX WATER', category: 'Utilities' },
  { keyword: 'SOUTHERN WATER', category: 'Utilities' },
  { keyword: 'AFFINITY WATER', category: 'Utilities' },
  // Telecoms (BT and VIRGIN MEDIA moved here from Utilities; trailing spaces on EE /O2 /BT  to
  // prevent false substring matches e.g. "COFFEE", "DEBTOR")
  { keyword: 'VODAFONE', category: 'Telecoms' },
  { keyword: 'EE ', category: 'Telecoms' },
  { keyword: 'O2 ', category: 'Telecoms' },
  { keyword: 'THREE', category: 'Telecoms' },
  { keyword: 'GIFFGAFF', category: 'Telecoms' },
  { keyword: 'BT ', category: 'Telecoms' },
  { keyword: 'VIRGIN MEDIA', category: 'Telecoms' },
  { keyword: 'TALKTALK', category: 'Telecoms' },
  { keyword: 'PLUSNET', category: 'Telecoms' },
  { keyword: 'ID MOBILE', category: 'Telecoms' },
  { keyword: 'SMARTY', category: 'Telecoms' },
  { keyword: 'LEBARA', category: 'Telecoms' },
  // Insurance
  { keyword: 'DIRECT LINE', category: 'Insurance' },
  { keyword: 'AVIVA', category: 'Insurance' },
  { keyword: 'LV=', category: 'Insurance' },
  { keyword: 'ADMIRAL', category: 'Insurance' },
  { keyword: 'AXA', category: 'Insurance' },
  // Income keywords that contain 'TAX' must precede TAX → Taxes
  { keyword: 'TAX CREDIT', category: 'Income' },
  { keyword: 'WORKING TAX', category: 'Income' },
  // Taxes (COUNCIL TAX REFUND before TAX to avoid broad TAX match swallowing it incorrectly)
  { keyword: 'HMRC', category: 'Taxes' },
  { keyword: 'COUNCIL TAX REFUND', category: 'Taxes' },
  { keyword: 'TAX', category: 'Taxes' },
  // Income
  { keyword: 'SALARY', category: 'Income' },
  { keyword: 'PAYROLL', category: 'Income' },
  { keyword: 'BACS CREDIT', category: 'Income' },
  { keyword: 'WAGES', category: 'Income' },
  { keyword: 'BANK CREDIT', category: 'Income' },
  { keyword: 'FASTER PAYMENT IN', category: 'Income' },
  { keyword: 'FASTER PAYMENT RECEIVED', category: 'Income' },
  { keyword: 'STANDING ORDER IN', category: 'Income' },
  { keyword: 'INTEREST PAID', category: 'Income' },
  { keyword: 'CASHBACK', category: 'Income' },
  { keyword: 'REFUND', category: 'Income' },
  { keyword: 'CHILD BENEFIT', category: 'Income' },
  { keyword: 'UNIVERSAL CREDIT', category: 'Income' },
  // Internal Transfer
  { keyword: 'TRANSFER TO', category: 'Internal Transfer' },
  { keyword: 'TRANSFER FROM', category: 'Internal Transfer' },
  { keyword: 'SAVINGS TRANSFER', category: 'Internal Transfer' },
  { keyword: 'PAYMENT RECEIVED', category: 'Internal Transfer' },
  { keyword: 'PAYMENT THANK YOU', category: 'Internal Transfer' },
  { keyword: 'BALANCE TRANSFER', category: 'Internal Transfer' },
  { keyword: 'DIRECT DEBIT PAYMENT', category: 'Internal Transfer' },
  { keyword: 'CREDIT CARD PAYMENT', category: 'Internal Transfer' },
];

export const REFERENCE_FORMAT_PROFILES: Omit<FormatProfileRecord, 'createdDate'>[] = [
  {
    type: 'formatProfile',
    profileName: 'Nationwide Current Account',
    detectionHints: {
      metadataRowCount: 4,
      dateFormat: 'DD Mon YYYY',
      headerSignatures: ['Paid out', 'Paid in', 'Balance'],
      confidenceThreshold: 0.8,
    },
    columnMappings: [
      { sourceHeader: 'Date', canonicalField: 'date', transform: 'parseDDMonYYYY' },
      { sourceHeader: 'Description', canonicalField: 'description' },
      { sourceHeader: 'Paid out', canonicalField: 'paidOut', transform: 'stripPound' },
      { sourceHeader: 'Paid in', canonicalField: 'paidIn', transform: 'stripPound' },
      { sourceHeader: 'Balance', canonicalField: 'balance', transform: 'stripPound' },
    ],
  },
  {
    type: 'formatProfile',
    profileName: 'Nationwide Credit Card',
    detectionHints: {
      metadataRowCount: 4,
      dateFormat: 'DD Mon YYYY',
      headerSignatures: ['Paid out', 'Paid in', 'Location'],
      confidenceThreshold: 0.8,
    },
    columnMappings: [
      { sourceHeader: 'Date', canonicalField: 'date', transform: 'parseDDMonYYYY' },
      { sourceHeader: 'Transactions', canonicalField: 'description' },
      { sourceHeader: 'Location', canonicalField: 'ignore' },
      { sourceHeader: 'Paid out', canonicalField: 'paidOut', transform: 'stripPound' },
      { sourceHeader: 'Paid in', canonicalField: 'paidIn', transform: 'stripPound' },
    ],
  },
  {
    type: 'formatProfile',
    profileName: 'NewDay Credit Card',
    detectionHints: {
      metadataRowCount: 0,
      dateFormat: 'DD/MM/YYYY',
      headerSignatures: ['Date', 'Description', 'Amount'],
      confidenceThreshold: 0.7,
    },
    columnMappings: [
      { sourceHeader: 'Date', canonicalField: 'date', transform: 'parseUKDate' },
      { sourceHeader: 'Description', canonicalField: 'description' },
      { sourceHeader: 'Amount', canonicalField: 'amount' },
    ],
  },
  {
    type: 'formatProfile',
    profileName: 'NewDay Credit Card v2',
    detectionHints: {
      metadataRowCount: 0,
      dateFormat: 'DD/MM/YYYY',
      headerSignatures: ['Note', 'Amount(GBP)'],
      confidenceThreshold: 0.7,
    },
    columnMappings: [
      { sourceHeader: 'Date', canonicalField: 'date', transform: 'parseUKDate' },
      { sourceHeader: 'Description', canonicalField: 'description' },
      { sourceHeader: 'Note', canonicalField: 'ignore' },
      { sourceHeader: 'Amount(GBP)', canonicalField: 'amount', transform: 'negateAmount' },
    ],
  },
];
